#site config
title: Nguyen Dang Nhat
subtitle: My Profile
description: My Profile
url: https://ndagnhat.github.io
heroimg: assets/img/hero-bg.jpg
herotitle: Hello, world!
herosubtitle: I'm Nguyen Dang Nhat, I'm a Developer, I'm a Freelancer

#page config tempate
# title:
# summary:
# noindex:
# permalink:
# thumbnail:
# categories:
# tags
# menu

#menu config
memuitems:
  - name: About
    url: "/"
    id: about
  
  - name: Products
    url: "/products"
    id: products
    
  - name: Stories
    url: "/stories"
    id: stories
    
  - name: Hire me!
    url: "/hireme"
    id: hireme
  

#abount me config
aboutme:
  photo: /assets/img/profile.jpg
  name: Nguyen Dang Nhat
  email: nhatnd9504@gmail.com
  phone: (+84)34 676 1576
  cv: /assets/cv/NguyenDangNhat1.pdf
  abouts: 
    - I'm a Deveoper and Freelancer in Hanoi, Viet Nam. 
    - Web developer with 4+ years of experience in Microsoft .NET technologies. 
    - Mobile developer with 1+ years of experience in Flutter. 
  skills: 
    - 💪 ASP.Net, Sharepoint, Flutter. 

#product config
products:
  title: My Products
  description: Helpful products. For everyone.
  thumbnail: /assets/img/products/products.png
  items: 
    - name: Money Daily
      description: Experience a fresh way to manage money.
      photo: /assets/img/products/sp1.png
      #url: /products
      
    - name: Amem - Gospel and catholic calendar
      description: For Christian. Read Gospel daily.
      photo: /assets/img/products/sp2.png
      #url: /products

#hire me config
hireme:
  title: Hire me!
  description: I'm Available For Freelance Work.
  thumbnail: /assets/img/stories/stories.jpg

#store config
stories:
  title: My Stories
  description: I have no words!
  thumbnail: /assets/img/stories/stories.jpg
