#site config
title: "Nguyen Dang Nhat"
subtitle: "My Portfolio"
description: "My father is farmer"
url: "https://ngdangnhat.github.io"

#page config tempate
# title:
# summary:
# noindex:
# permalink:
# thumbnail:
# categories:
# tags