#site config
title: "Nguyen Dang Nhat"
subtitle: "My Portfolio"
description: "My father is farmer"
url: "https://ngdangnhat.github.io"

#page config tempate
# title:
# summary:
# noindex:
# permalink:
# thumbnail:
# categories:
# tags
# menu

#menu config
memuitems:
  - name: Home
    url: "/"
    id: home
  
  - name: Products
    url: "/products"
    id: products
    
  - name: Stories
    url: "/stories"
    id: stories
    
  - name: Hire me!
    url: "/hireme"
    id: hireme
  

#abount me config
aboutme:
  photo: /assets/img/profile.jpg
  name: Nguyen Dang Nhat
  email: "dangnhatnguyen@outlook.com"
  phone: "(+84) 946 220495"
  cv: "/assets/cv/NguyenDangNhat.pdf"
  abouts: 
    - I'm a Deveoper and Freelancer in Hanoi, Viet Nam
    - Web developer with 4+ years of experience in Microsoft .NET technologies
    - Mobile developer with 1+ years of experience in Flutter
  skills: 
    - "💪 ASP.Net, Sharepoint, Flutter"

#product config
products:
  title: My Products
  description: Helpful products. For everyone.
  thumbnail: /assets/img/products/products.jpg
  items: 
    - name: Money Daily
      description: Experience a fresh way to manage money.
      photo: /assets/img/products/sp1.png
      url: /products
      
    - name: Amem - Gospel and catholic calendar
      description: For Christian. Read Gospel daily.
      photo: /assets/img/products/sp2.png
      url: /products

#hire me config
hireme:
  title: Hire me!
  description: I'm Available For Freelance Work.
  thumbnail: /assets/img/here_me/here_me.png

#store config
stories:
  title: My Stories
  description: Rảnh rỗi ngồi viết linh tinh
  thumbnail: /assets/img/stories/stories.jpg
